### ISSUE TITLE
Add GSoC students blogs to planet.coala-analyzer.org

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/engagement#11]
@AbdealiJK can you self assign and do this today?

**Comment by AbdealiJK** [comment]
Done (except hypothesist as the RSS link gives a 404)
I added the RSS Links to the Syndicate plugin. Do I need to create some author or something similar and link the RSS Link to the Author of the site ? (You don't seem to have done it for other blogs)

**Comment by sils1297** [comment]
@AbdealiJK just giving it a link to the blog works fine, it also usually figures out where to look for the feed by itself. Thanks! I corrected @hypothesist s feed.
