### ISSUE TITLE
Add Google Tracking to planet.coala-analyzer.org

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/engagement#12]
@AbdealiJK can you self assign and do this today?

**Comment by AbdealiJK** [comment]
It seems we already have a plugin names "WP Statistics" which is really nice. It doesnt track number of people viewing the RSS though - I wonder if it's possible to do that.

**Comment by AbdealiJK** [comment]
I have deleted the "coala - Planet" property from google analytics.
I am using:
 - WP Statistics - To measure number of people visitng site (This is quite low as it's a subscription site. This will not be needed when it gets merged with coala-website in @tushar-rishav 's GSoC project)
 - Simple Feed Stats - To see number of times the RSS feed is downloaded by someone (Google analytics cannot do this)
 - Post Notif - To see number of subscribers via email
