### ISSUE TITLE
Reach out to BitDefender for EuroPython SPonsoring

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/engagement#2]
CC @Adrianzatreanu @Nosferatul

**Comment by sils1297** [comment]
@Adrianzatreanu can you deal with this ASAP? This was intended to happen within a few days, not weeks originally.

**Comment by Adrianzatreanu** [comment]
yes, you're right, it's my bad. I have contacted a friend from the same organization i'm part of (that bitdefender sponsors sometimes) and he told me that they do not sponsor abroad finances or stuff like that, since they tried before. they only do in our country.
