### ISSUE TITLE
Create Graphic Advertisment for coala

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/engagement#35]
Read here : http://meta.stackoverflow.com/questions/327559/open-source-advertising-2h-2016

[Free Vote-Based Advertising for Open Source Projects](http://blog.stackoverflow.com/2009/12/free-vote-based-advertising-for-open-source-projects/)

**Comment by AbdealiJK** [comment]
Bump - someone should really do this. It's free advertising !

**Comment by sils1297** [comment]
This was done at http://meta.stackoverflow.com/questions/327559/open-source-advertising-2h-2016/333317#333317 - please upvote!

**Comment by sils1297** [comment]
Thanks to @beatrix-bodo for doing this!
