### ISSUE TITLE
StackOverflow Advert

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/engagement#37]
http://meta.stackoverflow.com/questions/327559/open-source-advertising-2h-2016

SO is saying they will give a free advert for an open source organization that's asking for more developers.
It is a great idea for us to participate. We need a advertisement poster/logo asap !

**Comment by mr-karan** [comment]
It's a dupe

**Comment by AbdealiJK** [comment]
Oops, duplicate of https://github.com/coala-analyzer/engagement/issues/35
