### ISSUE TITLE
add coala to https://github.com/vinta/awesome-python/blob/master/CONTRIBUTING.md

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/engagement#7]
add coala to https://github.com/vinta/awesome-python/blob/master/CONTRIBUTING.md

that project seems to be popular @Uran198 time to look into this?

**Comment by sils1297** [comment]
good to look at PRs that got accepted and see how they reasoned that they are "awesome"

**Comment by SanketDG** [comment]
I am pretty sure that `coala` would be accepted, the project solves a problem, has good code quality and is active.

**Comment by Uran198** [comment]
https://github.com/vinta/awesome-python/pull/622

**Comment by Uran198** [comment]
We've got merged in :smile:
