### ISSUE TITLE
Make a list of peoples twitter accounts

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/engagement#9]

**Comment by Makman2** [comment]
https://twitter.com/MakmanX64

**Comment by sils1297** [comment]
LSchuirmann for me

**Comment by Uran198** [comment]
https://twitter.com/ATovt

**Comment by SanketDG** [comment]
https://twiiter.com/SanketDG

**Comment by abhsag24** [comment]
https://twitter.com/RaizadaAbhay

**Comment by sils1297** [comment]
No really can somebody make a markdown table in the repo with the names, github and twitter?

**Comment by mr-karan** [comment]
http://twitter.com/karansharma1295

**Comment by arafsheikh** [comment]
https://twitter.com/arafsheikh

**Comment by djkonro** [comment]
https://twitter.com/djkonro35

**Comment by sils1297** [comment]
Can somebody put this list in the repo please and ping other people for their names? If somebody doesn't have twitter please list that explicitly so we don't ask that person multiple times.

**Comment by Makman2** [comment]
Where exactly? and which people to ask for? all contributors? maintainers?

**Comment by sils1297** [comment]
All. People who contribute so I might want to mention them in tweets.

Just a markdown or CSV in the repo. Really quick'n'simple.

**Comment by Makman2** [comment]
does wiki suffices?

**Comment by Makman2** [comment]
See https://github.com/coala-analyzer/engagement/wiki/People

**Comment by Adrianzatreanu** [comment]
moved here https://github.com/coala-analyzer/coala/wiki/Twitter-accounts
